### ISSUE TITLE
ImportError: No module named 'apiRequest'

### ISSUE THREAD

**Issue by Lithium876** [lhat-messorem/syntax_db#1]
Traceback (most recent call last):
  File "syntax.py", line 1, in <module>
    from syntaxdb import syntaxdb
  File "C:\Python34\lib\site-packages\syntaxdb\__init__.py", line 1, in <module>
    from syntaxdb import syntaxdb
  File "C:\Python34\lib\site-packages\syntaxdb\syntaxdb.py", line 4, in <module>
    import apiRequest

**Comment by Lithium876** [comment]
This is a python 3 error.

**Comment by tuanlha** [comment]
Yes, thank you. I think it should be absolute import to work with Python 3. But I just implement that module with Python 2, not Python 3 yet. I'll update Python 3 support later. Again, thank for your help.

**Comment by Lithium95** [comment]
The code looks simple if enough maybe we could collab on it if you don't mind
